# This is a basic workflow to help you get started with Actions

name: K8s Portfolio Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

    
jobs:
    deploy-on-push:
        runs-on : self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: install kctl
              run: 
                sudo apt-get update
                sudo snap install kubectl --classic
                kubectl --version           
            
            - name: minikube start
              run: |
                curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
                sudo dpkg -i minikube_latest_amd64.deb
                minikube start 
                minikube status 



            - name: apply k8s wordpress config files
              run: |
                kubectl apply -f mysql-secret.yaml
                kubectl apply -f mysql-pv-pvc.yaml
                kubectl apply -f mysql-statefulset.yaml
                kubectl apply -f mysql-service.yaml
                kubectl apply -f wordpress-pv-pvc.yaml
                kubectl apply -f wordpress-deployment.yaml
            - name: Sleep for 30 seconds
              run: sleep 200s
              shell: bash                         
                
            - name: check deployment 
              run: |
                kubectl get svc wordpress-service
                echo "---------------------Pods"
                kubectl get pods
                echo "---------------------deployments"
                kubectl get deployment
                echo "--------------------Services"
                minikube service --all 
                minikube logs

