# This is a basic workflow to help you get started with Actions

name: K8s Portfolio Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel


    
jobs:
    deploy-on-push:
        runs-on : self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: install kctl
              run: 
                sudo apt-get update
                sudo apt update
                sudo apt install snapd
                sudo snap install kubectl 
                kubectl --version   
                sudo usermod -a -G docker $USER && newgrp docker
            # - uses: docker-practice/actions-setup-docker@master
            #   timeout-minutes: 12
            # - run: |
            #     set -x

            #     docker version

            #     docker run --rm hello-world
            
            - name: minikube start
              run: |
                curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
                sudo dpkg -i minikube_latest_amd64.deb
                minikube start --driver=docker
                minikube status 

            - name: apply k8s wordpress config files
              run: |
                kubectl apply -f mysql-secret.yaml
                kubectl apply -f mysql-pv-pvc.yaml
                kubectl apply -f mysql-statefulset.yaml
                kubectl apply -f mysql-service.yaml
                kubectl apply -f wordpress-pv-pvc.yaml
                kubectl apply -f wordpress-deployment.yaml
                                
                
            - name: check deployment 
              run: |
                kubectl get svc wordpress-service
                echo "---------------------Pods"
                kubectl get pods
                echo "---------------------deployments"
                kubectl get deployment
                echo "--------------------Services"
                minikube service --all 
                minikube logs

